#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v5
# autospec commit: c02b2fe
#
# Source0 file verified with key 0xD7574483BB57B18D (jr@jriddell.org)
#
Name     : ktextaddons
Version  : 1.5.4
Release  : 8
URL      : https://download.kde.org/stable/ktextaddons/ktextaddons-1.5.4.tar.xz
Source0  : https://download.kde.org/stable/ktextaddons/ktextaddons-1.5.4.tar.xz
Source1  : https://download.kde.org/stable/ktextaddons/ktextaddons-1.5.4.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 LGPL-2.0 LGPL-2.1
Requires: ktextaddons-data = %{version}-%{release}
Requires: ktextaddons-lib = %{version}-%{release}
Requires: ktextaddons-license = %{version}-%{release}
Requires: ktextaddons-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : qtkeychain-dev
BuildRequires : syntax-highlighting-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
KTextAddons
=======
Various text handling addons
# Dependencies
- extra-cmake-modules

%package data
Summary: data components for the ktextaddons package.
Group: Data

%description data
data components for the ktextaddons package.


%package dev
Summary: dev components for the ktextaddons package.
Group: Development
Requires: ktextaddons-lib = %{version}-%{release}
Requires: ktextaddons-data = %{version}-%{release}
Provides: ktextaddons-devel = %{version}-%{release}
Requires: ktextaddons = %{version}-%{release}

%description dev
dev components for the ktextaddons package.


%package lib
Summary: lib components for the ktextaddons package.
Group: Libraries
Requires: ktextaddons-data = %{version}-%{release}
Requires: ktextaddons-license = %{version}-%{release}

%description lib
lib components for the ktextaddons package.


%package license
Summary: license components for the ktextaddons package.
Group: Default

%description license
license components for the ktextaddons package.


%package locales
Summary: locales components for the ktextaddons package.
Group: Default

%description locales
locales components for the ktextaddons package.


%prep
%setup -q -n ktextaddons-1.5.4
cd %{_builddir}/ktextaddons-1.5.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711665051
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DQT_MAJOR_VERSION=6
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DQT_MAJOR_VERSION=6
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1711665051
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ktextaddons
cp %{_builddir}/ktextaddons-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/ktextaddons/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/ktextaddons-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/ktextaddons/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/ktextaddons-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/ktextaddons/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/ktextaddons-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/ktextaddons/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/ktextaddons-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/ktextaddons/6f1f675aa5f6a2bbaa573b8343044b166be28399 || :
cp %{_builddir}/ktextaddons-%{version}/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/ktextaddons/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang libtextautocorrection
%find_lang libtextedittexttospeech
%find_lang libtextgrammarcheck
%find_lang libtexttranslator
%find_lang libtextaddonswidgets
%find_lang libtextcustomeditor
%find_lang libtextemoticons
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/qlogging-categories6/ktextaddons.categories
/usr/share/qlogging-categories6/ktextaddons.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/KF6/TextAddonsWidgets/TextAddonsWidgets/SelectSpecialCharDialog
/usr/include/KF6/TextAddonsWidgets/TextAddonsWidgets/SlideContainer
/usr/include/KF6/TextAddonsWidgets/textaddonswidgets/selectspecialchardialog.h
/usr/include/KF6/TextAddonsWidgets/textaddonswidgets/slidecontainer.h
/usr/include/KF6/TextAddonsWidgets/textaddonswidgets/textaddonswidgets_export.h
/usr/include/KF6/TextAddonsWidgets/textaddonswidgets_version.h
/usr/include/KF6/TextAutoCorrectionCore/TextAutoCorrectionCore/AutoCorrection
/usr/include/KF6/TextAutoCorrectionCore/TextAutoCorrectionCore/AutoCorrectionSettings
/usr/include/KF6/TextAutoCorrectionCore/TextAutoCorrectionCore/AutoCorrectionUtils
/usr/include/KF6/TextAutoCorrectionCore/TextAutoCorrectionCore/ImportAbstractAutocorrection
/usr/include/KF6/TextAutoCorrectionCore/TextAutoCorrectionCore/ImportKMailAutocorrection
/usr/include/KF6/TextAutoCorrectionCore/TextAutoCorrectionCore/ImportLibreOfficeAutocorrection
/usr/include/KF6/TextAutoCorrectionCore/TextAutoCorrectionCore/TextAutoCorrectionSettings
/usr/include/KF6/TextAutoCorrectionCore/textautocorrectioncore/autocorrection.h
/usr/include/KF6/TextAutoCorrectionCore/textautocorrectioncore/autocorrectionsettings.h
/usr/include/KF6/TextAutoCorrectionCore/textautocorrectioncore/autocorrectionutils.h
/usr/include/KF6/TextAutoCorrectionCore/textautocorrectioncore/importabstractautocorrection.h
/usr/include/KF6/TextAutoCorrectionCore/textautocorrectioncore/importkmailautocorrection.h
/usr/include/KF6/TextAutoCorrectionCore/textautocorrectioncore/importlibreofficeautocorrection.h
/usr/include/KF6/TextAutoCorrectionCore/textautocorrectioncore/textautocorrectioncore_export.h
/usr/include/KF6/TextAutoCorrectionCore/textautocorrectioncore/textautocorrectionsetting_base.h
/usr/include/KF6/TextAutoCorrectionCore/textautocorrectioncore/textautocorrectionsettings.h
/usr/include/KF6/TextAutoCorrectionCore/textautocorrectioncore_version.h
/usr/include/KF6/TextAutoCorrectionWidgets/TextAutoCorrectionWidgets/AutoCorrectionLanguage
/usr/include/KF6/TextAutoCorrectionWidgets/TextAutoCorrectionWidgets/AutoCorrectionTextEdit
/usr/include/KF6/TextAutoCorrectionWidgets/TextAutoCorrectionWidgets/AutoCorrectionWidget
/usr/include/KF6/TextAutoCorrectionWidgets/textautocorrectionwidgets/autocorrectionlanguage.h
/usr/include/KF6/TextAutoCorrectionWidgets/textautocorrectionwidgets/autocorrectiontextedit.h
/usr/include/KF6/TextAutoCorrectionWidgets/textautocorrectionwidgets/autocorrectionwidget.h
/usr/include/KF6/TextAutoCorrectionWidgets/textautocorrectionwidgets/textautocorrectionwidgets_export.h
/usr/include/KF6/TextAutoCorrectionWidgets/textautocorrectionwidgets_version.h
/usr/include/KF6/TextCustomEditor/TextCustomEditor/PlainTextEditFindBar
/usr/include/KF6/TextCustomEditor/TextCustomEditor/PlainTextEditor
/usr/include/KF6/TextCustomEditor/TextCustomEditor/PlainTextEditorWidget
/usr/include/KF6/TextCustomEditor/TextCustomEditor/PlainTextSyntaxSpellCheckingHighlighter
/usr/include/KF6/TextCustomEditor/TextCustomEditor/RichTextBrowser
/usr/include/KF6/TextCustomEditor/TextCustomEditor/RichTextBrowserFindBar
/usr/include/KF6/TextCustomEditor/TextCustomEditor/RichTextBrowserWidget
/usr/include/KF6/TextCustomEditor/TextCustomEditor/RichTextEditFindBar
/usr/include/KF6/TextCustomEditor/TextCustomEditor/RichTextEditor
/usr/include/KF6/TextCustomEditor/TextCustomEditor/RichTextEditorWidget
/usr/include/KF6/TextCustomEditor/TextCustomEditor/TextEditFindBarBase
/usr/include/KF6/TextCustomEditor/TextCustomEditor/TextEditorCompleter
/usr/include/KF6/TextCustomEditor/TextCustomEditor/TextGotoLineWidget
/usr/include/KF6/TextCustomEditor/textcustomeditor/plaintexteditfindbar.h
/usr/include/KF6/TextCustomEditor/textcustomeditor/plaintexteditor.h
/usr/include/KF6/TextCustomEditor/textcustomeditor/plaintexteditorwidget.h
/usr/include/KF6/TextCustomEditor/textcustomeditor/plaintextsyntaxspellcheckinghighlighter.h
/usr/include/KF6/TextCustomEditor/textcustomeditor/richtextbrowser.h
/usr/include/KF6/TextCustomEditor/textcustomeditor/richtextbrowserfindbar.h
/usr/include/KF6/TextCustomEditor/textcustomeditor/richtextbrowserwidget.h
/usr/include/KF6/TextCustomEditor/textcustomeditor/richtexteditfindbar.h
/usr/include/KF6/TextCustomEditor/textcustomeditor/richtexteditor.h
/usr/include/KF6/TextCustomEditor/textcustomeditor/richtexteditorwidget.h
/usr/include/KF6/TextCustomEditor/textcustomeditor/textcustomeditor_export.h
/usr/include/KF6/TextCustomEditor/textcustomeditor/texteditfindbarbase.h
/usr/include/KF6/TextCustomEditor/textcustomeditor/texteditorcompleter.h
/usr/include/KF6/TextCustomEditor/textcustomeditor/textgotolinewidget.h
/usr/include/KF6/TextCustomEditor/textcustomeditor_version.h
/usr/include/KF6/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeech
/usr/include/KF6/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeechActions
/usr/include/KF6/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeechConfigDialog
/usr/include/KF6/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeechConfigWidget
/usr/include/KF6/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeechContainerWidget
/usr/include/KF6/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeechInterface
/usr/include/KF6/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeechWidget
/usr/include/KF6/TextEditTextToSpeech/textedittexttospeech/textedittexttospeech_export.h
/usr/include/KF6/TextEditTextToSpeech/textedittexttospeech/texttospeech.h
/usr/include/KF6/TextEditTextToSpeech/textedittexttospeech/texttospeechactions.h
/usr/include/KF6/TextEditTextToSpeech/textedittexttospeech/texttospeechconfigdialog.h
/usr/include/KF6/TextEditTextToSpeech/textedittexttospeech/texttospeechconfigwidget.h
/usr/include/KF6/TextEditTextToSpeech/textedittexttospeech/texttospeechcontainerwidget.h
/usr/include/KF6/TextEditTextToSpeech/textedittexttospeech/texttospeechinterface.h
/usr/include/KF6/TextEditTextToSpeech/textedittexttospeech/texttospeechwidget.h
/usr/include/KF6/TextEditTextToSpeech/textedittexttospeech_version.h
/usr/include/KF6/TextEmoticonsCore/TextEmoticonsCore/CustomEmoji
/usr/include/KF6/TextEmoticonsCore/TextEmoticonsCore/CustomEmojiIconManager
/usr/include/KF6/TextEmoticonsCore/TextEmoticonsCore/EmojiModel
/usr/include/KF6/TextEmoticonsCore/TextEmoticonsCore/EmojiModelManager
/usr/include/KF6/TextEmoticonsCore/TextEmoticonsCore/EmojiProxyModel
/usr/include/KF6/TextEmoticonsCore/TextEmoticonsCore/EmoticonCategory
/usr/include/KF6/TextEmoticonsCore/TextEmoticonsCore/EmoticonUnicodeUtils
/usr/include/KF6/TextEmoticonsCore/TextEmoticonsCore/RunningAnimatedImage
/usr/include/KF6/TextEmoticonsCore/TextEmoticonsCore/UnicodeEmoticon
/usr/include/KF6/TextEmoticonsCore/TextEmoticonsCore/UnicodeEmoticonManager
/usr/include/KF6/TextEmoticonsCore/TextEmoticonsCore/UnicodeEmoticonParser
/usr/include/KF6/TextEmoticonsCore/textemoticonscore/customemoji.h
/usr/include/KF6/TextEmoticonsCore/textemoticonscore/customemojiiconmanager.h
/usr/include/KF6/TextEmoticonsCore/textemoticonscore/emojimodel.h
/usr/include/KF6/TextEmoticonsCore/textemoticonscore/emojimodelmanager.h
/usr/include/KF6/TextEmoticonsCore/textemoticonscore/emojiproxymodel.h
/usr/include/KF6/TextEmoticonsCore/textemoticonscore/emoticoncategory.h
/usr/include/KF6/TextEmoticonsCore/textemoticonscore/emoticonunicodeutils.h
/usr/include/KF6/TextEmoticonsCore/textemoticonscore/runninganimatedimage.h
/usr/include/KF6/TextEmoticonsCore/textemoticonscore/textemoticonscore_export.h
/usr/include/KF6/TextEmoticonsCore/textemoticonscore/unicodeemoticon.h
/usr/include/KF6/TextEmoticonsCore/textemoticonscore/unicodeemoticonmanager.h
/usr/include/KF6/TextEmoticonsCore/textemoticonscore/unicodeemoticonparser.h
/usr/include/KF6/TextEmoticonsCore/textemoticonscore_version.h
/usr/include/KF6/TextEmoticonsWidgets/TextEmoticonsWidgets/EmoticonTextEditAction
/usr/include/KF6/TextEmoticonsWidgets/TextEmoticonsWidgets/EmoticonTextEditSelector
/usr/include/KF6/TextEmoticonsWidgets/textemoticonswidgets/emoticontexteditaction.h
/usr/include/KF6/TextEmoticonsWidgets/textemoticonswidgets/emoticontexteditselector.h
/usr/include/KF6/TextEmoticonsWidgets/textemoticonswidgets/textemoticonswidgets_export.h
/usr/include/KF6/TextEmoticonsWidgets/textemoticonswidgets_version.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/GrammalecteConfigDialog
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/GrammalecteConfigWidget
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/GrammalecteGenerateConfigOptionJob
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/GrammalecteManager
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/GrammalecteResultJob
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/GrammalecteResultWidget
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/GrammarAction
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/GrammarError
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/GrammarResultTextEdit
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/GrammarResultWidget
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/LanguageToolComboBox
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/LanguageToolConfigDialog
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/LanguageToolConfigWidget
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/LanguageToolGetListOfLanguageJob
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/LanguageToolManager
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/LanguageToolResultWidget
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/grammalecteconfigdialog.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/grammalecteconfigwidget.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/grammalectegenerateconfigoptionjob.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/grammalectemanager.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/grammalecteresultjob.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/grammalecteresultwidget.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/grammaraction.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/grammarerror.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/grammarresulttextedit.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/grammarresultwidget.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/languagetoolcombobox.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/languagetoolconfigdialog.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/languagetoolconfigwidget.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/languagetoolgetlistoflanguagejob.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/languagetoolmanager.h
/usr/include/KF6/TextGrammarCheck/TextGrammarCheck/languagetoolresultwidget.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/grammalecteconfigdialog.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/grammalecteconfigwidget.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/grammalectegenerateconfigoptionjob.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/grammalectemanager.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/grammalecteresultjob.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/grammalecteresultwidget.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/grammaraction.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/grammarerror.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/grammarresulttextedit.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/grammarresultwidget.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/languagetoolcombobox.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/languagetoolconfigdialog.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/languagetoolconfigwidget.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/languagetoolgetlistoflanguagejob.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/languagetoolmanager.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/languagetoolresultwidget.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck/textgrammarcheck_export.h
/usr/include/KF6/TextGrammarCheck/textgrammarcheck_version.h
/usr/include/KF6/TextTranslator/TextTranslator/TranslatorConfigureDialog
/usr/include/KF6/TextTranslator/TextTranslator/TranslatorConfigureLanguageListWidget
/usr/include/KF6/TextTranslator/TextTranslator/TranslatorConfigureListsWidget
/usr/include/KF6/TextTranslator/TextTranslator/TranslatorEngineAccessManager
/usr/include/KF6/TextTranslator/TextTranslator/TranslatorEngineClient
/usr/include/KF6/TextTranslator/TextTranslator/TranslatorEngineLoader
/usr/include/KF6/TextTranslator/TextTranslator/TranslatorEnginePlugin
/usr/include/KF6/TextTranslator/TextTranslator/TranslatorMenu
/usr/include/KF6/TextTranslator/TextTranslator/TranslatorUtil
/usr/include/KF6/TextTranslator/TextTranslator/TranslatorWidget
/usr/include/KF6/TextTranslator/TextTranslator/translatorconfiguredialog.h
/usr/include/KF6/TextTranslator/TextTranslator/translatorconfigurelanguagelistwidget.h
/usr/include/KF6/TextTranslator/TextTranslator/translatorconfigurelistswidget.h
/usr/include/KF6/TextTranslator/TextTranslator/translatorengineaccessmanager.h
/usr/include/KF6/TextTranslator/TextTranslator/translatorengineclient.h
/usr/include/KF6/TextTranslator/TextTranslator/translatorengineloader.h
/usr/include/KF6/TextTranslator/TextTranslator/translatorengineplugin.h
/usr/include/KF6/TextTranslator/TextTranslator/translatormenu.h
/usr/include/KF6/TextTranslator/TextTranslator/translatorutil.h
/usr/include/KF6/TextTranslator/TextTranslator/translatorwidget.h
/usr/include/KF6/TextTranslator/texttranslator/texttranslator_export.h
/usr/include/KF6/TextTranslator/texttranslator/translatorconfiguredialog.h
/usr/include/KF6/TextTranslator/texttranslator/translatorconfigurelanguagelistwidget.h
/usr/include/KF6/TextTranslator/texttranslator/translatorconfigurelistswidget.h
/usr/include/KF6/TextTranslator/texttranslator/translatorengineaccessmanager.h
/usr/include/KF6/TextTranslator/texttranslator/translatorengineclient.h
/usr/include/KF6/TextTranslator/texttranslator/translatorengineloader.h
/usr/include/KF6/TextTranslator/texttranslator/translatorengineplugin.h
/usr/include/KF6/TextTranslator/texttranslator/translatormenu.h
/usr/include/KF6/TextTranslator/texttranslator/translatorutil.h
/usr/include/KF6/TextTranslator/texttranslator/translatorwidget.h
/usr/include/KF6/TextTranslator/texttranslator_version.h
/usr/include/KF6/TextUtils/TextUtils/ConvertText
/usr/include/KF6/TextUtils/textutils/converttext.h
/usr/include/KF6/TextUtils/textutils/textutils_export.h
/usr/include/KF6/TextUtils/textutils_version.h
/usr/lib64/cmake/KF6TextAddonsWidgets/KF6TextAddonsWidgetsConfig.cmake
/usr/lib64/cmake/KF6TextAddonsWidgets/KF6TextAddonsWidgetsConfigVersion.cmake
/usr/lib64/cmake/KF6TextAddonsWidgets/KF6TextAddonsWidgetsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6TextAddonsWidgets/KF6TextAddonsWidgetsTargets.cmake
/usr/lib64/cmake/KF6TextAutoCorrectionCore/KF6TextAutoCorrectionCoreConfig.cmake
/usr/lib64/cmake/KF6TextAutoCorrectionCore/KF6TextAutoCorrectionCoreConfigVersion.cmake
/usr/lib64/cmake/KF6TextAutoCorrectionCore/KF6TextAutoCorrectionCoreTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6TextAutoCorrectionCore/KF6TextAutoCorrectionCoreTargets.cmake
/usr/lib64/cmake/KF6TextAutoCorrectionWidgets/KF6TextAutoCorrectionWidgetsConfig.cmake
/usr/lib64/cmake/KF6TextAutoCorrectionWidgets/KF6TextAutoCorrectionWidgetsConfigVersion.cmake
/usr/lib64/cmake/KF6TextAutoCorrectionWidgets/KF6TextAutoCorrectionWidgetsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6TextAutoCorrectionWidgets/KF6TextAutoCorrectionWidgetsTargets.cmake
/usr/lib64/cmake/KF6TextCustomEditor/KF6TextCustomEditorConfig.cmake
/usr/lib64/cmake/KF6TextCustomEditor/KF6TextCustomEditorConfigVersion.cmake
/usr/lib64/cmake/KF6TextCustomEditor/KF6TextCustomEditorTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6TextCustomEditor/KF6TextCustomEditorTargets.cmake
/usr/lib64/cmake/KF6TextEditTextToSpeech/KF6TextEditTextToSpeechConfig.cmake
/usr/lib64/cmake/KF6TextEditTextToSpeech/KF6TextEditTextToSpeechConfigVersion.cmake
/usr/lib64/cmake/KF6TextEditTextToSpeech/KF6TextEditTextToSpeechTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6TextEditTextToSpeech/KF6TextEditTextToSpeechTargets.cmake
/usr/lib64/cmake/KF6TextEmoticonsCore/KF6TextEmoticonsCoreConfig.cmake
/usr/lib64/cmake/KF6TextEmoticonsCore/KF6TextEmoticonsCoreConfigVersion.cmake
/usr/lib64/cmake/KF6TextEmoticonsCore/KF6TextEmoticonsCoreTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6TextEmoticonsCore/KF6TextEmoticonsCoreTargets.cmake
/usr/lib64/cmake/KF6TextEmoticonsWidgets/KF6TextEmoticonsWidgetsConfig.cmake
/usr/lib64/cmake/KF6TextEmoticonsWidgets/KF6TextEmoticonsWidgetsConfigVersion.cmake
/usr/lib64/cmake/KF6TextEmoticonsWidgets/KF6TextEmoticonsWidgetsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6TextEmoticonsWidgets/KF6TextEmoticonsWidgetsTargets.cmake
/usr/lib64/cmake/KF6TextGrammarCheck/KF6TextGrammarCheckConfig.cmake
/usr/lib64/cmake/KF6TextGrammarCheck/KF6TextGrammarCheckConfigVersion.cmake
/usr/lib64/cmake/KF6TextGrammarCheck/KF6TextGrammarCheckTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6TextGrammarCheck/KF6TextGrammarCheckTargets.cmake
/usr/lib64/cmake/KF6TextTranslator/KF6TextTranslatorConfig.cmake
/usr/lib64/cmake/KF6TextTranslator/KF6TextTranslatorConfigVersion.cmake
/usr/lib64/cmake/KF6TextTranslator/KF6TextTranslatorTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6TextTranslator/KF6TextTranslatorTargets.cmake
/usr/lib64/cmake/KF6TextUtils/KF6TextUtilsConfig.cmake
/usr/lib64/cmake/KF6TextUtils/KF6TextUtilsConfigVersion.cmake
/usr/lib64/cmake/KF6TextUtils/KF6TextUtilsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6TextUtils/KF6TextUtilsTargets.cmake
/usr/lib64/libKF6TextAddonsWidgets.so
/usr/lib64/libKF6TextAutoCorrectionCore.so
/usr/lib64/libKF6TextAutoCorrectionWidgets.so
/usr/lib64/libKF6TextCustomEditor.so
/usr/lib64/libKF6TextEditTextToSpeech.so
/usr/lib64/libKF6TextEmoticonsCore.so
/usr/lib64/libKF6TextEmoticonsWidgets.so
/usr/lib64/libKF6TextGrammarCheck.so
/usr/lib64/libKF6TextTranslator.so
/usr/lib64/libKF6TextUtils.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKF6TextAddonsWidgets.so.1.5.4
/V3/usr/lib64/libKF6TextAutoCorrectionCore.so.1.5.4
/V3/usr/lib64/libKF6TextAutoCorrectionWidgets.so.1.5.4
/V3/usr/lib64/libKF6TextCustomEditor.so.1.5.4
/V3/usr/lib64/libKF6TextEditTextToSpeech.so.1.5.4
/V3/usr/lib64/libKF6TextEmoticonsCore.so.1.5.4
/V3/usr/lib64/libKF6TextEmoticonsWidgets.so.1.5.4
/V3/usr/lib64/libKF6TextGrammarCheck.so.1.5.4
/V3/usr/lib64/libKF6TextTranslator.so.1.5.4
/V3/usr/lib64/libKF6TextUtils.so.1.5.4
/V3/usr/lib64/qt6/plugins/designer/textcustomeditor.so
/V3/usr/lib64/qt6/plugins/designer/texttranslatorwidgets6.so
/V3/usr/lib64/qt6/plugins/kf6/translator/translator_bing.so
/V3/usr/lib64/qt6/plugins/kf6/translator/translator_deepl.so
/V3/usr/lib64/qt6/plugins/kf6/translator/translator_google.so
/V3/usr/lib64/qt6/plugins/kf6/translator/translator_libretranslate.so
/V3/usr/lib64/qt6/plugins/kf6/translator/translator_lingva.so
/V3/usr/lib64/qt6/plugins/kf6/translator/translator_yandex.so
/usr/lib64/libKF6TextAddonsWidgets.so.1
/usr/lib64/libKF6TextAddonsWidgets.so.1.5.4
/usr/lib64/libKF6TextAutoCorrectionCore.so.1
/usr/lib64/libKF6TextAutoCorrectionCore.so.1.5.4
/usr/lib64/libKF6TextAutoCorrectionWidgets.so.1
/usr/lib64/libKF6TextAutoCorrectionWidgets.so.1.5.4
/usr/lib64/libKF6TextCustomEditor.so.1
/usr/lib64/libKF6TextCustomEditor.so.1.5.4
/usr/lib64/libKF6TextEditTextToSpeech.so.1
/usr/lib64/libKF6TextEditTextToSpeech.so.1.5.4
/usr/lib64/libKF6TextEmoticonsCore.so.1
/usr/lib64/libKF6TextEmoticonsCore.so.1.5.4
/usr/lib64/libKF6TextEmoticonsWidgets.so.1
/usr/lib64/libKF6TextEmoticonsWidgets.so.1.5.4
/usr/lib64/libKF6TextGrammarCheck.so.1
/usr/lib64/libKF6TextGrammarCheck.so.1.5.4
/usr/lib64/libKF6TextTranslator.so.1
/usr/lib64/libKF6TextTranslator.so.1.5.4
/usr/lib64/libKF6TextUtils.so.1
/usr/lib64/libKF6TextUtils.so.1.5.4
/usr/lib64/qt6/plugins/designer/textcustomeditor.so
/usr/lib64/qt6/plugins/designer/texttranslatorwidgets6.so
/usr/lib64/qt6/plugins/kf6/translator/translator_bing.so
/usr/lib64/qt6/plugins/kf6/translator/translator_deepl.so
/usr/lib64/qt6/plugins/kf6/translator/translator_google.so
/usr/lib64/qt6/plugins/kf6/translator/translator_libretranslate.so
/usr/lib64/qt6/plugins/kf6/translator/translator_lingva.so
/usr/lib64/qt6/plugins/kf6/translator/translator_yandex.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ktextaddons/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/ktextaddons/6f1f675aa5f6a2bbaa573b8343044b166be28399
/usr/share/package-licenses/ktextaddons/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4
/usr/share/package-licenses/ktextaddons/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/ktextaddons/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/ktextaddons/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files locales -f libtextautocorrection.lang -f libtextedittexttospeech.lang -f libtextgrammarcheck.lang -f libtexttranslator.lang -f libtextaddonswidgets.lang -f libtextcustomeditor.lang -f libtextemoticons.lang
%defattr(-,root,root,-)

