#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
# Source0 file verified with key 0xF061DEBCC7EBD805 (montel@kde.org)
#
Name     : ktextaddons
Version  : 1.5.2
Release  : 5
URL      : https://download.kde.org/stable/ktextaddons/ktextaddons-1.5.2.tar.xz
Source0  : https://download.kde.org/stable/ktextaddons/ktextaddons-1.5.2.tar.xz
Source1  : https://download.kde.org/stable/ktextaddons/ktextaddons-1.5.2.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 LGPL-2.0 LGPL-2.1
Requires: ktextaddons-data = %{version}-%{release}
Requires: ktextaddons-lib = %{version}-%{release}
Requires: ktextaddons-license = %{version}-%{release}
Requires: ktextaddons-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : syntax-highlighting-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
SPDX-License-Identifier: BSD-3-Clause

%package data
Summary: data components for the ktextaddons package.
Group: Data

%description data
data components for the ktextaddons package.


%package dev
Summary: dev components for the ktextaddons package.
Group: Development
Requires: ktextaddons-lib = %{version}-%{release}
Requires: ktextaddons-data = %{version}-%{release}
Provides: ktextaddons-devel = %{version}-%{release}
Requires: ktextaddons = %{version}-%{release}

%description dev
dev components for the ktextaddons package.


%package lib
Summary: lib components for the ktextaddons package.
Group: Libraries
Requires: ktextaddons-data = %{version}-%{release}
Requires: ktextaddons-license = %{version}-%{release}

%description lib
lib components for the ktextaddons package.


%package license
Summary: license components for the ktextaddons package.
Group: Default

%description license
license components for the ktextaddons package.


%package locales
Summary: locales components for the ktextaddons package.
Group: Default

%description locales
locales components for the ktextaddons package.


%prep
%setup -q -n ktextaddons-1.5.2
cd %{_builddir}/ktextaddons-1.5.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1697473445
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1697473445
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ktextaddons
cp %{_builddir}/ktextaddons-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/ktextaddons/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/ktextaddons-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/ktextaddons/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/ktextaddons-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/ktextaddons/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/ktextaddons-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/ktextaddons/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/ktextaddons-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/ktextaddons/6f1f675aa5f6a2bbaa573b8343044b166be28399 || :
cp %{_builddir}/ktextaddons-%{version}/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/ktextaddons/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
%find_lang libtextautocorrection
%find_lang libtextedittexttospeech
%find_lang libtextgrammarcheck
%find_lang libtexttranslator
%find_lang libtextaddonswidgets
%find_lang libtextcustomeditor
%find_lang libtextemoticons
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/qlogging-categories5/ktextaddons.categories
/usr/share/qlogging-categories5/ktextaddons.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/TextAddonsWidgets/TextAddonsWidgets/LineEditCatchReturnKey
/usr/include/KF5/TextAddonsWidgets/TextAddonsWidgets/SelectSpecialCharDialog
/usr/include/KF5/TextAddonsWidgets/TextAddonsWidgets/SlideContainer
/usr/include/KF5/TextAddonsWidgets/textaddonswidgets/lineeditcatchreturnkey.h
/usr/include/KF5/TextAddonsWidgets/textaddonswidgets/selectspecialchardialog.h
/usr/include/KF5/TextAddonsWidgets/textaddonswidgets/slidecontainer.h
/usr/include/KF5/TextAddonsWidgets/textaddonswidgets/textaddonswidgets_export.h
/usr/include/KF5/TextAddonsWidgets/textaddonswidgets_version.h
/usr/include/KF5/TextAutoCorrectionCore/TextAutoCorrectionCore/AutoCorrection
/usr/include/KF5/TextAutoCorrectionCore/TextAutoCorrectionCore/AutoCorrectionSettings
/usr/include/KF5/TextAutoCorrectionCore/TextAutoCorrectionCore/AutoCorrectionUtils
/usr/include/KF5/TextAutoCorrectionCore/TextAutoCorrectionCore/ImportAbstractAutocorrection
/usr/include/KF5/TextAutoCorrectionCore/TextAutoCorrectionCore/ImportKMailAutocorrection
/usr/include/KF5/TextAutoCorrectionCore/TextAutoCorrectionCore/ImportLibreOfficeAutocorrection
/usr/include/KF5/TextAutoCorrectionCore/TextAutoCorrectionCore/TextAutoCorrectionSettings
/usr/include/KF5/TextAutoCorrectionCore/textautocorrectioncore/autocorrection.h
/usr/include/KF5/TextAutoCorrectionCore/textautocorrectioncore/autocorrectionsettings.h
/usr/include/KF5/TextAutoCorrectionCore/textautocorrectioncore/autocorrectionutils.h
/usr/include/KF5/TextAutoCorrectionCore/textautocorrectioncore/importabstractautocorrection.h
/usr/include/KF5/TextAutoCorrectionCore/textautocorrectioncore/importkmailautocorrection.h
/usr/include/KF5/TextAutoCorrectionCore/textautocorrectioncore/importlibreofficeautocorrection.h
/usr/include/KF5/TextAutoCorrectionCore/textautocorrectioncore/textautocorrectioncore_export.h
/usr/include/KF5/TextAutoCorrectionCore/textautocorrectioncore/textautocorrectionsetting_base.h
/usr/include/KF5/TextAutoCorrectionCore/textautocorrectioncore/textautocorrectionsettings.h
/usr/include/KF5/TextAutoCorrectionCore/textautocorrectioncore_version.h
/usr/include/KF5/TextAutoCorrectionWidgets/TextAutoCorrectionWidgets/AutoCorrectionLanguage
/usr/include/KF5/TextAutoCorrectionWidgets/TextAutoCorrectionWidgets/AutoCorrectionTextEdit
/usr/include/KF5/TextAutoCorrectionWidgets/TextAutoCorrectionWidgets/AutoCorrectionWidget
/usr/include/KF5/TextAutoCorrectionWidgets/textautocorrectionwidgets/autocorrectionlanguage.h
/usr/include/KF5/TextAutoCorrectionWidgets/textautocorrectionwidgets/autocorrectiontextedit.h
/usr/include/KF5/TextAutoCorrectionWidgets/textautocorrectionwidgets/autocorrectionwidget.h
/usr/include/KF5/TextAutoCorrectionWidgets/textautocorrectionwidgets/textautocorrectionwidgets_export.h
/usr/include/KF5/TextAutoCorrectionWidgets/textautocorrectionwidgets_version.h
/usr/include/KF5/TextCustomEditor/TextCustomEditor/PlainTextEditFindBar
/usr/include/KF5/TextCustomEditor/TextCustomEditor/PlainTextEditor
/usr/include/KF5/TextCustomEditor/TextCustomEditor/PlainTextEditorWidget
/usr/include/KF5/TextCustomEditor/TextCustomEditor/PlainTextSyntaxSpellCheckingHighlighter
/usr/include/KF5/TextCustomEditor/TextCustomEditor/RichTextBrowser
/usr/include/KF5/TextCustomEditor/TextCustomEditor/RichTextBrowserFindBar
/usr/include/KF5/TextCustomEditor/TextCustomEditor/RichTextBrowserWidget
/usr/include/KF5/TextCustomEditor/TextCustomEditor/RichTextEditFindBar
/usr/include/KF5/TextCustomEditor/TextCustomEditor/RichTextEditor
/usr/include/KF5/TextCustomEditor/TextCustomEditor/RichTextEditorWidget
/usr/include/KF5/TextCustomEditor/TextCustomEditor/TextEditFindBarBase
/usr/include/KF5/TextCustomEditor/TextCustomEditor/TextEditorCompleter
/usr/include/KF5/TextCustomEditor/TextCustomEditor/TextGotoLineWidget
/usr/include/KF5/TextCustomEditor/textcustomeditor/plaintexteditfindbar.h
/usr/include/KF5/TextCustomEditor/textcustomeditor/plaintexteditor.h
/usr/include/KF5/TextCustomEditor/textcustomeditor/plaintexteditorwidget.h
/usr/include/KF5/TextCustomEditor/textcustomeditor/plaintextsyntaxspellcheckinghighlighter.h
/usr/include/KF5/TextCustomEditor/textcustomeditor/richtextbrowser.h
/usr/include/KF5/TextCustomEditor/textcustomeditor/richtextbrowserfindbar.h
/usr/include/KF5/TextCustomEditor/textcustomeditor/richtextbrowserwidget.h
/usr/include/KF5/TextCustomEditor/textcustomeditor/richtexteditfindbar.h
/usr/include/KF5/TextCustomEditor/textcustomeditor/richtexteditor.h
/usr/include/KF5/TextCustomEditor/textcustomeditor/richtexteditorwidget.h
/usr/include/KF5/TextCustomEditor/textcustomeditor/textcustomeditor_export.h
/usr/include/KF5/TextCustomEditor/textcustomeditor/texteditfindbarbase.h
/usr/include/KF5/TextCustomEditor/textcustomeditor/texteditorcompleter.h
/usr/include/KF5/TextCustomEditor/textcustomeditor/textgotolinewidget.h
/usr/include/KF5/TextCustomEditor/textcustomeditor_version.h
/usr/include/KF5/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeech
/usr/include/KF5/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeechActions
/usr/include/KF5/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeechConfigDialog
/usr/include/KF5/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeechConfigWidget
/usr/include/KF5/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeechContainerWidget
/usr/include/KF5/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeechInterface
/usr/include/KF5/TextEditTextToSpeech/TextEditTextToSpeech/TextToSpeechWidget
/usr/include/KF5/TextEditTextToSpeech/textedittexttospeech/textedittexttospeech_export.h
/usr/include/KF5/TextEditTextToSpeech/textedittexttospeech/texttospeech.h
/usr/include/KF5/TextEditTextToSpeech/textedittexttospeech/texttospeechactions.h
/usr/include/KF5/TextEditTextToSpeech/textedittexttospeech/texttospeechconfigdialog.h
/usr/include/KF5/TextEditTextToSpeech/textedittexttospeech/texttospeechconfigwidget.h
/usr/include/KF5/TextEditTextToSpeech/textedittexttospeech/texttospeechcontainerwidget.h
/usr/include/KF5/TextEditTextToSpeech/textedittexttospeech/texttospeechinterface.h
/usr/include/KF5/TextEditTextToSpeech/textedittexttospeech/texttospeechwidget.h
/usr/include/KF5/TextEditTextToSpeech/textedittexttospeech_version.h
/usr/include/KF5/TextEmoticonsCore/TextEmoticonsCore/CustomEmoji
/usr/include/KF5/TextEmoticonsCore/TextEmoticonsCore/CustomEmojiIconManager
/usr/include/KF5/TextEmoticonsCore/TextEmoticonsCore/EmojiModel
/usr/include/KF5/TextEmoticonsCore/TextEmoticonsCore/EmojiModelManager
/usr/include/KF5/TextEmoticonsCore/TextEmoticonsCore/EmojiProxyModel
/usr/include/KF5/TextEmoticonsCore/TextEmoticonsCore/EmoticonCategory
/usr/include/KF5/TextEmoticonsCore/TextEmoticonsCore/EmoticonUnicodeUtils
/usr/include/KF5/TextEmoticonsCore/TextEmoticonsCore/RunningAnimatedImage
/usr/include/KF5/TextEmoticonsCore/TextEmoticonsCore/UnicodeEmoticon
/usr/include/KF5/TextEmoticonsCore/TextEmoticonsCore/UnicodeEmoticonManager
/usr/include/KF5/TextEmoticonsCore/TextEmoticonsCore/UnicodeEmoticonParser
/usr/include/KF5/TextEmoticonsCore/textemoticonscore/customemoji.h
/usr/include/KF5/TextEmoticonsCore/textemoticonscore/customemojiiconmanager.h
/usr/include/KF5/TextEmoticonsCore/textemoticonscore/emojimodel.h
/usr/include/KF5/TextEmoticonsCore/textemoticonscore/emojimodelmanager.h
/usr/include/KF5/TextEmoticonsCore/textemoticonscore/emojiproxymodel.h
/usr/include/KF5/TextEmoticonsCore/textemoticonscore/emoticoncategory.h
/usr/include/KF5/TextEmoticonsCore/textemoticonscore/emoticonunicodeutils.h
/usr/include/KF5/TextEmoticonsCore/textemoticonscore/runninganimatedimage.h
/usr/include/KF5/TextEmoticonsCore/textemoticonscore/textemoticonscore_export.h
/usr/include/KF5/TextEmoticonsCore/textemoticonscore/unicodeemoticon.h
/usr/include/KF5/TextEmoticonsCore/textemoticonscore/unicodeemoticonmanager.h
/usr/include/KF5/TextEmoticonsCore/textemoticonscore/unicodeemoticonparser.h
/usr/include/KF5/TextEmoticonsCore/textemoticonscore_version.h
/usr/include/KF5/TextEmoticonsWidgets/TextEmoticonsWidgets/EmoticonTextEditAction
/usr/include/KF5/TextEmoticonsWidgets/TextEmoticonsWidgets/EmoticonTextEditSelector
/usr/include/KF5/TextEmoticonsWidgets/textemoticonswidgets/emoticontexteditaction.h
/usr/include/KF5/TextEmoticonsWidgets/textemoticonswidgets/emoticontexteditselector.h
/usr/include/KF5/TextEmoticonsWidgets/textemoticonswidgets/textemoticonswidgets_export.h
/usr/include/KF5/TextEmoticonsWidgets/textemoticonswidgets_version.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/GrammalecteConfigDialog
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/GrammalecteConfigWidget
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/GrammalecteGenerateConfigOptionJob
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/GrammalecteManager
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/GrammalecteResultJob
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/GrammalecteResultWidget
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/GrammarAction
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/GrammarError
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/GrammarResultTextEdit
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/GrammarResultWidget
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/LanguageToolComboBox
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/LanguageToolConfigDialog
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/LanguageToolConfigWidget
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/LanguageToolGetListOfLanguageJob
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/LanguageToolManager
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/LanguageToolResultWidget
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/grammalecteconfigdialog.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/grammalecteconfigwidget.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/grammalectegenerateconfigoptionjob.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/grammalectemanager.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/grammalecteresultjob.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/grammalecteresultwidget.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/grammaraction.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/grammarerror.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/grammarresulttextedit.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/grammarresultwidget.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/languagetoolcombobox.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/languagetoolconfigdialog.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/languagetoolconfigwidget.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/languagetoolgetlistoflanguagejob.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/languagetoolmanager.h
/usr/include/KF5/TextGrammarCheck/TextGrammarCheck/languagetoolresultwidget.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/grammalecteconfigdialog.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/grammalecteconfigwidget.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/grammalectegenerateconfigoptionjob.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/grammalectemanager.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/grammalecteresultjob.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/grammalecteresultwidget.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/grammaraction.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/grammarerror.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/grammarresulttextedit.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/grammarresultwidget.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/languagetoolcombobox.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/languagetoolconfigdialog.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/languagetoolconfigwidget.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/languagetoolgetlistoflanguagejob.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/languagetoolmanager.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/languagetoolresultwidget.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck/textgrammarcheck_export.h
/usr/include/KF5/TextGrammarCheck/textgrammarcheck_version.h
/usr/include/KF5/TextTranslator/TextTranslator/TranslatorConfigureDialog
/usr/include/KF5/TextTranslator/TextTranslator/TranslatorConfigureLanguageListWidget
/usr/include/KF5/TextTranslator/TextTranslator/TranslatorConfigureListsWidget
/usr/include/KF5/TextTranslator/TextTranslator/TranslatorEngineAccessManager
/usr/include/KF5/TextTranslator/TextTranslator/TranslatorEngineClient
/usr/include/KF5/TextTranslator/TextTranslator/TranslatorEngineLoader
/usr/include/KF5/TextTranslator/TextTranslator/TranslatorEnginePlugin
/usr/include/KF5/TextTranslator/TextTranslator/TranslatorMenu
/usr/include/KF5/TextTranslator/TextTranslator/TranslatorUtil
/usr/include/KF5/TextTranslator/TextTranslator/TranslatorWidget
/usr/include/KF5/TextTranslator/TextTranslator/translatorconfiguredialog.h
/usr/include/KF5/TextTranslator/TextTranslator/translatorconfigurelanguagelistwidget.h
/usr/include/KF5/TextTranslator/TextTranslator/translatorconfigurelistswidget.h
/usr/include/KF5/TextTranslator/TextTranslator/translatorengineaccessmanager.h
/usr/include/KF5/TextTranslator/TextTranslator/translatorengineclient.h
/usr/include/KF5/TextTranslator/TextTranslator/translatorengineloader.h
/usr/include/KF5/TextTranslator/TextTranslator/translatorengineplugin.h
/usr/include/KF5/TextTranslator/TextTranslator/translatormenu.h
/usr/include/KF5/TextTranslator/TextTranslator/translatorutil.h
/usr/include/KF5/TextTranslator/TextTranslator/translatorwidget.h
/usr/include/KF5/TextTranslator/texttranslator/texttranslator_export.h
/usr/include/KF5/TextTranslator/texttranslator/translatorconfiguredialog.h
/usr/include/KF5/TextTranslator/texttranslator/translatorconfigurelanguagelistwidget.h
/usr/include/KF5/TextTranslator/texttranslator/translatorconfigurelistswidget.h
/usr/include/KF5/TextTranslator/texttranslator/translatorengineaccessmanager.h
/usr/include/KF5/TextTranslator/texttranslator/translatorengineclient.h
/usr/include/KF5/TextTranslator/texttranslator/translatorengineloader.h
/usr/include/KF5/TextTranslator/texttranslator/translatorengineplugin.h
/usr/include/KF5/TextTranslator/texttranslator/translatormenu.h
/usr/include/KF5/TextTranslator/texttranslator/translatorutil.h
/usr/include/KF5/TextTranslator/texttranslator/translatorwidget.h
/usr/include/KF5/TextTranslator/texttranslator_version.h
/usr/include/KF5/TextUtils/TextUtils/ConvertText
/usr/include/KF5/TextUtils/textutils/converttext.h
/usr/include/KF5/TextUtils/textutils/textutils_export.h
/usr/include/KF5/TextUtils/textutils_version.h
/usr/lib64/cmake/KF5TextAddonsWidgets/KF5TextAddonsWidgetsConfig.cmake
/usr/lib64/cmake/KF5TextAddonsWidgets/KF5TextAddonsWidgetsConfigVersion.cmake
/usr/lib64/cmake/KF5TextAddonsWidgets/KF5TextAddonsWidgetsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5TextAddonsWidgets/KF5TextAddonsWidgetsTargets.cmake
/usr/lib64/cmake/KF5TextAutoCorrectionCore/KF5TextAutoCorrectionCoreConfig.cmake
/usr/lib64/cmake/KF5TextAutoCorrectionCore/KF5TextAutoCorrectionCoreConfigVersion.cmake
/usr/lib64/cmake/KF5TextAutoCorrectionCore/KF5TextAutoCorrectionCoreTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5TextAutoCorrectionCore/KF5TextAutoCorrectionCoreTargets.cmake
/usr/lib64/cmake/KF5TextAutoCorrectionWidgets/KF5TextAutoCorrectionWidgetsConfig.cmake
/usr/lib64/cmake/KF5TextAutoCorrectionWidgets/KF5TextAutoCorrectionWidgetsConfigVersion.cmake
/usr/lib64/cmake/KF5TextAutoCorrectionWidgets/KF5TextAutoCorrectionWidgetsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5TextAutoCorrectionWidgets/KF5TextAutoCorrectionWidgetsTargets.cmake
/usr/lib64/cmake/KF5TextCustomEditor/KF5TextCustomEditorConfig.cmake
/usr/lib64/cmake/KF5TextCustomEditor/KF5TextCustomEditorConfigVersion.cmake
/usr/lib64/cmake/KF5TextCustomEditor/KF5TextCustomEditorTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5TextCustomEditor/KF5TextCustomEditorTargets.cmake
/usr/lib64/cmake/KF5TextEditTextToSpeech/KF5TextEditTextToSpeechConfig.cmake
/usr/lib64/cmake/KF5TextEditTextToSpeech/KF5TextEditTextToSpeechConfigVersion.cmake
/usr/lib64/cmake/KF5TextEditTextToSpeech/KF5TextEditTextToSpeechTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5TextEditTextToSpeech/KF5TextEditTextToSpeechTargets.cmake
/usr/lib64/cmake/KF5TextEmoticonsCore/KF5TextEmoticonsCoreConfig.cmake
/usr/lib64/cmake/KF5TextEmoticonsCore/KF5TextEmoticonsCoreConfigVersion.cmake
/usr/lib64/cmake/KF5TextEmoticonsCore/KF5TextEmoticonsCoreTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5TextEmoticonsCore/KF5TextEmoticonsCoreTargets.cmake
/usr/lib64/cmake/KF5TextEmoticonsWidgets/KF5TextEmoticonsWidgetsConfig.cmake
/usr/lib64/cmake/KF5TextEmoticonsWidgets/KF5TextEmoticonsWidgetsConfigVersion.cmake
/usr/lib64/cmake/KF5TextEmoticonsWidgets/KF5TextEmoticonsWidgetsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5TextEmoticonsWidgets/KF5TextEmoticonsWidgetsTargets.cmake
/usr/lib64/cmake/KF5TextGrammarCheck/KF5TextGrammarCheckConfig.cmake
/usr/lib64/cmake/KF5TextGrammarCheck/KF5TextGrammarCheckConfigVersion.cmake
/usr/lib64/cmake/KF5TextGrammarCheck/KF5TextGrammarCheckTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5TextGrammarCheck/KF5TextGrammarCheckTargets.cmake
/usr/lib64/cmake/KF5TextTranslator/KF5TextTranslatorConfig.cmake
/usr/lib64/cmake/KF5TextTranslator/KF5TextTranslatorConfigVersion.cmake
/usr/lib64/cmake/KF5TextTranslator/KF5TextTranslatorTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5TextTranslator/KF5TextTranslatorTargets.cmake
/usr/lib64/cmake/KF5TextUtils/KF5TextUtilsConfig.cmake
/usr/lib64/cmake/KF5TextUtils/KF5TextUtilsConfigVersion.cmake
/usr/lib64/cmake/KF5TextUtils/KF5TextUtilsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5TextUtils/KF5TextUtilsTargets.cmake
/usr/lib64/libKF5TextAddonsWidgets.so
/usr/lib64/libKF5TextAutoCorrectionCore.so
/usr/lib64/libKF5TextAutoCorrectionWidgets.so
/usr/lib64/libKF5TextCustomEditor.so
/usr/lib64/libKF5TextEditTextToSpeech.so
/usr/lib64/libKF5TextEmoticonsCore.so
/usr/lib64/libKF5TextEmoticonsWidgets.so
/usr/lib64/libKF5TextGrammarCheck.so
/usr/lib64/libKF5TextTranslator.so
/usr/lib64/libKF5TextUtils.so
/usr/lib64/qt5/mkspecs/modules/qt_TextAutoCorrectionCore.pri
/usr/lib64/qt5/mkspecs/modules/qt_TextAutoCorrectionWidgets.pri
/usr/lib64/qt5/mkspecs/modules/qt_TextEditTextToSpeech.pri
/usr/lib64/qt5/mkspecs/modules/qt_TextGrammarCheck.pri
/usr/lib64/qt5/mkspecs/modules/qt_TextTranslator.pri
/usr/lib64/qt5/mkspecs/modules/qt_textaddonswidgets.pri
/usr/lib64/qt5/mkspecs/modules/qt_textcustomeditor.pri
/usr/lib64/qt5/mkspecs/modules/qt_textemoticonscore.pri
/usr/lib64/qt5/mkspecs/modules/qt_textemoticonswidgets.pri
/usr/lib64/qt5/mkspecs/modules/qt_textutils.pri

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKF5TextAddonsWidgets.so.1.5.2
/V3/usr/lib64/libKF5TextAutoCorrectionCore.so.1.5.2
/V3/usr/lib64/libKF5TextAutoCorrectionWidgets.so.1.5.2
/V3/usr/lib64/libKF5TextCustomEditor.so.1.5.2
/V3/usr/lib64/libKF5TextEditTextToSpeech.so.1.5.2
/V3/usr/lib64/libKF5TextEmoticonsCore.so.1.5.2
/V3/usr/lib64/libKF5TextEmoticonsWidgets.so.1.5.2
/V3/usr/lib64/libKF5TextGrammarCheck.so.1.5.2
/V3/usr/lib64/libKF5TextTranslator.so.1.5.2
/V3/usr/lib64/libKF5TextUtils.so.1.5.2
/V3/usr/lib64/qt5/plugins/designer/textcustomeditor.so
/V3/usr/lib64/qt5/plugins/designer/texttranslatorwidgets5.so
/V3/usr/lib64/qt5/plugins/kf5/translator/translator_bing.so
/V3/usr/lib64/qt5/plugins/kf5/translator/translator_deepl.so
/V3/usr/lib64/qt5/plugins/kf5/translator/translator_google.so
/V3/usr/lib64/qt5/plugins/kf5/translator/translator_libretranslate.so
/V3/usr/lib64/qt5/plugins/kf5/translator/translator_lingva.so
/V3/usr/lib64/qt5/plugins/kf5/translator/translator_yandex.so
/usr/lib64/libKF5TextAddonsWidgets.so.1
/usr/lib64/libKF5TextAddonsWidgets.so.1.5.2
/usr/lib64/libKF5TextAutoCorrectionCore.so.1
/usr/lib64/libKF5TextAutoCorrectionCore.so.1.5.2
/usr/lib64/libKF5TextAutoCorrectionWidgets.so.1
/usr/lib64/libKF5TextAutoCorrectionWidgets.so.1.5.2
/usr/lib64/libKF5TextCustomEditor.so.1
/usr/lib64/libKF5TextCustomEditor.so.1.5.2
/usr/lib64/libKF5TextEditTextToSpeech.so.1
/usr/lib64/libKF5TextEditTextToSpeech.so.1.5.2
/usr/lib64/libKF5TextEmoticonsCore.so.1
/usr/lib64/libKF5TextEmoticonsCore.so.1.5.2
/usr/lib64/libKF5TextEmoticonsWidgets.so.1
/usr/lib64/libKF5TextEmoticonsWidgets.so.1.5.2
/usr/lib64/libKF5TextGrammarCheck.so.1
/usr/lib64/libKF5TextGrammarCheck.so.1.5.2
/usr/lib64/libKF5TextTranslator.so.1
/usr/lib64/libKF5TextTranslator.so.1.5.2
/usr/lib64/libKF5TextUtils.so.1
/usr/lib64/libKF5TextUtils.so.1.5.2
/usr/lib64/qt5/plugins/designer/textcustomeditor.so
/usr/lib64/qt5/plugins/designer/texttranslatorwidgets5.so
/usr/lib64/qt5/plugins/kf5/translator/translator_bing.so
/usr/lib64/qt5/plugins/kf5/translator/translator_deepl.so
/usr/lib64/qt5/plugins/kf5/translator/translator_google.so
/usr/lib64/qt5/plugins/kf5/translator/translator_libretranslate.so
/usr/lib64/qt5/plugins/kf5/translator/translator_lingva.so
/usr/lib64/qt5/plugins/kf5/translator/translator_yandex.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ktextaddons/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/ktextaddons/6f1f675aa5f6a2bbaa573b8343044b166be28399
/usr/share/package-licenses/ktextaddons/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4
/usr/share/package-licenses/ktextaddons/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/ktextaddons/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/ktextaddons/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files locales -f libtextautocorrection.lang -f libtextedittexttospeech.lang -f libtextgrammarcheck.lang -f libtexttranslator.lang -f libtextaddonswidgets.lang -f libtextcustomeditor.lang -f libtextemoticons.lang
%defattr(-,root,root,-)

